#include<stdio.h>
#include<conio.h>
void main()
{
	int a[3][3],i,j,a1[3][3],a2[3][3];
	clrscr();
	for(i=0;i<3;i++)
	{
		for(j=0;j<3;j++)
		{
			printf("Enter the value a[%d][%d]:",i,j);
			scanf("%d",&a[i][j]);
		}
	}
	clrscr();
	printf("\n\n");
	for(i=0;i<3;i++)
	{
		for(j=0;j<3;j++)
		{
			printf("Enter the value a1[%d][%d]:",i,j);
			scanf("%d",&a1[i][j]);
		}
	}
	clrscr();
	for(i=0;i<3;i++)
	{
		for(j=0;j<3;j++)
		{
			printf("%d\t",a[i][j]);
		}
		printf("\n");
	}
	printf("\n\n");
	for(i=0;i<3;i++)
	{
		for(j=0;j<3;j++)
		{
			printf("%d\t",a1[i][j]);
		}
		printf("\n");
	}
	printf("\n\n");
	for(i=0;i<3;i++)
	{
		for(j=0;j<3;j++)
		{
			a2[i][j]=a[i][j]*a1[i][j]+a[i+1][j]+a1[i+2][j];
			printf("%d\t",a2[i][j]);
		}
		printf("\n");
	}
	getch();
}